[package]
name = "header_accumulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssz_rs = "0.9.0"
ssz_rs_derive = "0.9.0"
